# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ikJ626Brfd7dRq4ZFeIEYIqM1uSki22t
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(page_title="NIFTY 50 Dashboard", layout="wide")

st.title("📊 NIFTY 50 Stock Market Dashboard")

# Download NIFTY 50 data
nifty50_tickers = [
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "LT.NS", "SBIN.NS", "KOTAKBANK.NS",
    "AXISBANK.NS", "ASIANPAINT.NS", "BAJFINANCE.NS", "BHARTIARTL.NS",
    "HCLTECH.NS", "SUNPHARMA.NS", "MARUTI.NS", "NTPC.NS", "TITAN.NS",
    "ULTRACEMCO.NS", "WIPRO.NS", "TECHM.NS", "POWERGRID.NS", "NESTLEIND.NS",
    "JSWSTEEL.NS", "TATASTEEL.NS", "ADANIENT.NS", "COALINDIA.NS", "BAJAJFINSV.NS",
    "DIVISLAB.NS", "GRASIM.NS", "HDFCLIFE.NS", "CIPLA.NS", "SBILIFE.NS",
    "BRITANNIA.NS", "EICHERMOT.NS", "HEROMOTOCO.NS", "BAJAJ-AUTO.NS",
    "INDUSINDBK.NS", "BPCL.NS", "SHREECEM.NS", "DRREDDY.NS", "HINDALCO.NS",
    "ONGC.NS", "TATAMOTORS.NS", "APOLLOHOSP.NS", "M&M.NS", "UPL.NS", "ADANIPORTS.NS"
]

st.sidebar.header("Dashboard Controls")
start_date = st.sidebar.date_input("Start Date", pd.to_datetime("2020-01-01"))
end_date = st.sidebar.date_input("End Date", pd.to_datetime("2025-01-01"))

st.write("Fetching data... this may take a while ⏳")
data = yf.download(nifty50_tickers, start=start_date, end=end_date)
data.dropna(inplace=True)

# Show raw data
st.subheader("📂 Raw Stock Data")
st.dataframe(data.head())

# Calculate returns
returns = data["Close"].pct_change().dropna()
log_returns = np.log(1 + returns).dropna()

st.subheader("📈 Summary Statistics")
st.write(returns.describe())

# Correlation heatmap
st.subheader("🔥 Correlation Heatmap")
fig, ax = plt.subplots(figsize=(12, 6))
sns.heatmap(returns.corr(), annot=False, cmap="coolwarm", ax=ax)
st.pyplot(fig)

# Stock price trend
st.subheader("📉 Stock Price Trend")
selected_stock = st.selectbox("Choose a stock", nifty50_tickers)
fig2, ax2 = plt.subplots(figsize=(12, 6))
ax2.plot(data["Close"][selected_stock], label=selected_stock)
ax2.set_title(f"{selected_stock} Closing Price")
ax2.legend()
st.pyplot(fig2)

# Daily returns distribution
st.subheader("📊 Daily Returns Distribution")
fig3, ax3 = plt.subplots(figsize=(10, 5))
sns.histplot(returns[selected_stock], bins=50, kde=True, ax=ax3)
ax3.set_title(f"{selected_stock} Daily Returns")
st.pyplot(fig3)